/**
 * Item/shaft catalog — the runtime source of truth for the balance table in
 * `docs/games/tower-throwback.md` ("Item roster & balance table" +
 * "Upgrade paths"). Data-only: placement legality lives in placement.ts,
 * availability = f(star, map) via the helpers below.
 */

import type {
  ItemDef,
  ItemKind,
  MapDefinition,
  ShaftDef,
  ShaftKind,
  StarLevel,
  UpgradePath,
} from '../gameTypes'

export const ITEM_DEFS: Record<ItemKind, ItemDef> = {
  slab: {
    kind: 'slab',
    name: 'Floor',
    category: 'structure',
    width: 1,
    storeys: 1,
    cost: 50,
    perTile: true,
    maintPerDay: 0,
    starRequired: 1,
    vertical: 'undergroundAllowed',
  },
  lobby: {
    kind: 'lobby',
    name: 'Lobby',
    category: 'structure',
    width: 1,
    storeys: 1,
    cost: 300,
    perTile: true,
    maintPerDay: 5,
    starRequired: 1,
    vertical: 'groundOnly',
  },
  skylobby: {
    kind: 'skylobby',
    name: 'Skylobby',
    category: 'structure',
    width: 1,
    storeys: 1,
    cost: 1_500,
    perTile: true,
    maintPerDay: 15,
    starRequired: 1,
    vertical: 'undergroundAllowed',
  },
  skybridge: {
    kind: 'skybridge',
    name: 'Skybridge',
    category: 'structure',
    width: 1,
    storeys: 1,
    cost: 4_000,
    perTile: true,
    maintPerDay: 10,
    starRequired: 4,
  },
  stairs: {
    kind: 'stairs',
    name: 'Stairs',
    category: 'transit',
    width: 2,
    storeys: 1,
    cost: 5_000,
    maintPerDay: 10,
    starRequired: 1,
  },
  escalator: {
    kind: 'escalator',
    name: 'Escalator',
    category: 'transit',
    width: 4,
    storeys: 1,
    cost: 12_000,
    maintPerDay: 50,
    starRequired: 2,
    noise: { level: 8, radiusTiles: 5 },
  },
  officeS: {
    kind: 'officeS',
    name: 'Office (S)',
    category: 'office',
    width: 6,
    storeys: 1,
    cost: 20_000,
    maintPerDay: 0,
    income: { type: 'rent', perDay: 400 },
    capacity: 4,
    starRequired: 1,
    affinityGroup: 'office',
    noiseSensitivity: 0.5,
  },
  officeM: {
    kind: 'officeM',
    name: 'Office (M)',
    category: 'office',
    width: 9,
    storeys: 1,
    cost: 40_000,
    maintPerDay: 0,
    income: { type: 'rent', perDay: 900 },
    capacity: 8,
    starRequired: 2,
    affinityGroup: 'office',
    noiseSensitivity: 0.5,
  },
  officeL: {
    kind: 'officeL',
    name: 'Office (L)',
    category: 'office',
    width: 12,
    storeys: 1,
    cost: 80_000,
    maintPerDay: 0,
    income: { type: 'rent', perDay: 2_000 },
    capacity: 16,
    starRequired: 4,
    affinityGroup: 'office',
    noiseSensitivity: 0.5,
  },
  aptStudio: {
    kind: 'aptStudio',
    name: 'Apartment (Studio)',
    category: 'residential',
    width: 4,
    storeys: 1,
    cost: 15_000,
    maintPerDay: 0,
    income: { type: 'rent', perDay: 200 },
    capacity: 2,
    starRequired: 1,
    affinityGroup: 'residential',
    noiseSensitivity: 2.0,
  },
  apt1br: {
    kind: 'apt1br',
    name: 'Apartment (1BR)',
    category: 'residential',
    width: 6,
    storeys: 1,
    cost: 25_000,
    maintPerDay: 0,
    income: { type: 'rent', perDay: 350 },
    capacity: 3,
    starRequired: 2,
    affinityGroup: 'residential',
    noiseSensitivity: 2.0,
  },
  apt2br: {
    kind: 'apt2br',
    name: 'Apartment (2BR)',
    category: 'residential',
    width: 8,
    storeys: 1,
    cost: 40_000,
    maintPerDay: 0,
    income: { type: 'rent', perDay: 600 },
    capacity: 5,
    starRequired: 3,
    affinityGroup: 'residential',
    noiseSensitivity: 2.0,
  },
  aptPenthouse: {
    kind: 'aptPenthouse',
    name: 'Apartment (Penthouse)',
    category: 'residential',
    width: 16,
    storeys: 1,
    cost: 150_000,
    maintPerDay: 0,
    income: { type: 'rent', perDay: 2_500 },
    capacity: 6,
    starRequired: 5,
    affinityGroup: 'residential',
    noiseSensitivity: 2.0,
  },
  restroom: {
    kind: 'restroom',
    name: 'Restroom',
    category: 'services',
    width: 4,
    storeys: 1,
    cost: 10_000,
    maintPerDay: 100,
    starRequired: 1,
    vertical: 'undergroundAllowed',
  },
  shop: {
    kind: 'shop',
    name: 'Shop',
    category: 'commerce',
    width: 8,
    storeys: 1,
    cost: 30_000,
    maintPerDay: 150,
    income: { type: 'perVisit', amount: 15 },
    starRequired: 1,
    vertical: 'undergroundAllowed',
    noise: { level: 6, radiusTiles: 6 },
    affinityGroup: 'retail',
  },
  fastfood: {
    kind: 'fastfood',
    name: 'Fast Food',
    category: 'commerce',
    width: 12,
    storeys: 1,
    cost: 50_000,
    maintPerDay: 250,
    income: { type: 'perVisit', amount: 10 },
    starRequired: 1,
    vertical: 'undergroundAllowed',
    noise: { level: 12, radiusTiles: 8 },
    affinityGroup: 'food',
  },
  foodCourt: {
    kind: 'foodCourt',
    name: 'Food Court',
    category: 'commerce',
    width: 16,
    storeys: 1,
    cost: 80_000,
    maintPerDay: 400,
    income: { type: 'perVisit', amount: 8 },
    starRequired: 2,
    noise: { level: 14, radiusTiles: 10 },
    affinityGroup: 'food',
  },
  restaurant: {
    kind: 'restaurant',
    name: 'Restaurant',
    category: 'commerce',
    width: 10,
    storeys: 1,
    cost: 60_000,
    maintPerDay: 300,
    income: { type: 'perVisit', amount: 25 },
    starRequired: 2,
    noise: { level: 10, radiusTiles: 8 },
    affinityGroup: 'food',
  },
  fancyRestaurant: {
    kind: 'fancyRestaurant',
    name: 'Fancy Restaurant',
    category: 'commerce',
    width: 12,
    storeys: 1,
    cost: 120_000,
    maintPerDay: 500,
    income: { type: 'perVisit', amount: 60 },
    starRequired: 4,
    noise: { level: 8, radiusTiles: 8 },
    affinityGroup: 'food',
  },
  movieTheater: {
    kind: 'movieTheater',
    name: 'Movie Theater',
    category: 'commerce',
    width: 20,
    storeys: 2,
    cost: 200_000,
    maintPerDay: 800,
    income: { type: 'perVisit', amount: 20 },
    starRequired: 3,
    noise: { level: 16, radiusTiles: 12 },
    affinityGroup: 'entertainment',
  },
  fitness: {
    kind: 'fitness',
    name: 'Fitness Center',
    category: 'commerce',
    width: 12,
    storeys: 1,
    cost: 70_000,
    maintPerDay: 300,
    income: { type: 'perVisit', amount: 10 },
    starRequired: 3,
    noise: { level: 10, radiusTiles: 8 },
    affinityGroup: 'entertainment',
  },
  pool: {
    kind: 'pool',
    name: 'Swimming Pool',
    category: 'commerce',
    width: 20,
    storeys: 2,
    cost: 200_000,
    maintPerDay: 700,
    income: { type: 'perVisit', amount: 8 },
    starRequired: 4,
    affinityGroup: 'entertainment',
  },
  spa: {
    kind: 'spa',
    name: 'Spa',
    category: 'commerce',
    width: 12,
    storeys: 1,
    cost: 150_000,
    maintPerDay: 500,
    income: { type: 'perVisit', amount: 40 },
    starRequired: 4,
    affinityGroup: 'entertainment',
  },
  conferenceCenter: {
    kind: 'conferenceCenter',
    name: 'Conference Center',
    category: 'commerce',
    width: 24,
    storeys: 2,
    cost: 300_000,
    maintPerDay: 800,
    income: { type: 'perVisit', amount: 15 },
    starRequired: 3,
  },
  eventSpace: {
    kind: 'eventSpace',
    name: 'Event Space',
    category: 'commerce',
    width: 30,
    storeys: 2,
    cost: 500_000,
    maintPerDay: 1_000,
    income: { type: 'perEvent', amount: 5_000 },
    starRequired: 5,
    noise: { level: 18, radiusTiles: 14 },
  },
  hotelReception: {
    kind: 'hotelReception',
    name: 'Hotel Reception',
    category: 'hotel',
    width: 10,
    storeys: 1,
    cost: 50_000,
    maintPerDay: 300,
    starRequired: 3,
    affinityGroup: 'hotel',
  },
  hotel1p: {
    kind: 'hotel1p',
    name: 'Hotel Room (1p)',
    category: 'hotel',
    width: 4,
    storeys: 1,
    cost: 20_000,
    maintPerDay: 20,
    income: { type: 'perNight', amount: 350 },
    capacity: 1,
    starRequired: 3,
    affinityGroup: 'hotel',
    noiseSensitivity: 1.0,
  },
  hotel2p: {
    kind: 'hotel2p',
    name: 'Hotel Room (2p)',
    category: 'hotel',
    width: 6,
    storeys: 1,
    cost: 35_000,
    maintPerDay: 20,
    income: { type: 'perNight', amount: 600 },
    capacity: 2,
    starRequired: 3,
    affinityGroup: 'hotel',
    noiseSensitivity: 1.0,
  },
  hotelSuite: {
    kind: 'hotelSuite',
    name: 'Hotel Suite',
    category: 'hotel',
    width: 10,
    storeys: 1,
    cost: 100_000,
    maintPerDay: 20,
    income: { type: 'perNight', amount: 1_800 },
    capacity: 2,
    starRequired: 3,
    affinityGroup: 'hotel',
    noiseSensitivity: 1.0,
  },
  housekeeping: {
    kind: 'housekeeping',
    name: 'Housekeeping',
    category: 'services',
    width: 8,
    storeys: 1,
    cost: 30_000,
    maintPerDay: 200,
    starRequired: 3,
  },
  trashRoom: {
    kind: 'trashRoom',
    name: 'Trash Room',
    category: 'services',
    width: 6,
    storeys: 1,
    cost: 25_000,
    maintPerDay: 100,
    starRequired: 3,
    vertical: 'undergroundAllowed',
  },
  recyclingCenter: {
    kind: 'recyclingCenter',
    name: 'Recycling Center',
    category: 'services',
    width: 20,
    storeys: 1,
    cost: 150_000,
    maintPerDay: 400,
    starRequired: 4,
    vertical: 'undergroundOnly',
  },
  parkingRamp: {
    kind: 'parkingRamp',
    name: 'Parking Ramp',
    category: 'services',
    width: 6,
    storeys: 1,
    cost: 30_000,
    maintPerDay: 100,
    starRequired: 3,
    vertical: 'undergroundOnly',
  },
  parkingSpace: {
    kind: 'parkingSpace',
    name: 'Parking Space',
    category: 'services',
    width: 2,
    storeys: 1,
    cost: 3_000,
    maintPerDay: 10,
    starRequired: 3,
    vertical: 'undergroundOnly',
  },
  subway: {
    kind: 'subway',
    name: 'Subway Station',
    category: 'transit',
    width: 30,
    storeys: 1,
    cost: 300_000,
    maintPerDay: 500,
    starRequired: 3,
    vertical: 'b10Only',
  },
  securityOffice: {
    kind: 'securityOffice',
    name: 'Security Office',
    category: 'services',
    width: 10,
    storeys: 1,
    cost: 50_000,
    maintPerDay: 300,
    starRequired: 4,
  },
  medicalClinic: {
    kind: 'medicalClinic',
    name: 'Medical Clinic',
    category: 'services',
    width: 12,
    storeys: 1,
    cost: 80_000,
    maintPerDay: 300,
    income: { type: 'perVisit', amount: 30 },
    operates: true,
    starRequired: 4,
  },
  cathedral: {
    kind: 'cathedral',
    name: 'Cathedral',
    category: 'special',
    width: 30,
    storeys: 2,
    cost: 1_000_000,
    maintPerDay: 0,
    starRequired: 5,
    vertical: 'terminalFloor',
    allowsFloorRangeOverhang: true,
  },
  observationDeck: {
    kind: 'observationDeck',
    name: 'Observation Deck',
    category: 'special',
    width: 24,
    storeys: 2,
    cost: 1_000_000,
    maintPerDay: 0,
    starRequired: 5,
    vertical: 'terminalFloor',
    allowsFloorRangeOverhang: true,
    cantileverTiles: 6,
  },
}

export const SHAFT_DEFS: Record<ShaftKind, ShaftDef> = {
  standard: {
    kind: 'standard',
    name: 'Elevator',
    width: 2,
    baseCost: 50_000,
    costPerFloor: 5000,
    maintPerCarPerDay: 200,
    carCapacity: 20,
    maxCars: 6,
    carCost: 40_000,
    maxReachFloors: 30,
  },
  express: {
    kind: 'express',
    name: 'Express Elevator',
    width: 3,
    baseCost: 200_000,
    costPerFloor: 10_000,
    maintPerCarPerDay: 500,
    carCapacity: 40,
    maxCars: 4,
    carCost: 40_000,
    maxStops: 5,
  },
  service: {
    kind: 'service',
    name: 'Service Elevator',
    width: 2,
    baseCost: 80_000,
    costPerFloor: 5_000,
    maintPerCarPerDay: 150,
    carCapacity: 10,
    maxCars: 4,
    carCost: 40_000,
    serviceOnly: true,
  },
  glass: {
    kind: 'glass',
    name: 'Glass Elevator',
    width: 2,
    baseCost: 150_000,
    costPerFloor: 8_000,
    maintPerCarPerDay: 400,
    carCapacity: 15,
    maxCars: 2,
    carCost: 40_000,
    exterior: true,
  },
}

export const UPGRADE_PATHS: readonly UpgradePath[] = [
  {
    id: 'fastfood-to-restaurant',
    appliesTo: ['fastfood'],
    toKind: 'restaurant',
    cost: 40_000,
    starRequired: 2,
    label: 'Upgrade to Restaurant',
  },
  {
    id: 'restaurant-to-fancy',
    appliesTo: ['restaurant'],
    toKind: 'fancyRestaurant',
    cost: 80_000,
    starRequired: 4,
    label: 'Upgrade to Fancy Restaurant',
  },
  {
    id: 'hotel1p-to-luxury',
    appliesTo: ['hotel1p'],
    toGrade: 'luxury',
    cost: 30_000,
    starRequired: 4,
    label: 'Upgrade to Luxury Room (1p)',
  },
  {
    id: 'hotel2p-to-luxury',
    appliesTo: ['hotel2p'],
    toGrade: 'luxury',
    cost: 50_000,
    starRequired: 4,
    label: 'Upgrade to Luxury Room (2p)',
  },
  {
    id: 'hotelsuite-to-luxury',
    appliesTo: ['hotelSuite'],
    toGrade: 'luxury',
    cost: 80_000,
    starRequired: 4,
    label: 'Upgrade to Luxury Suite',
  },
  {
    id: 'trashroom-to-recycling',
    appliesTo: ['trashRoom'],
    toGrade: 'recycling',
    cost: 60_000,
    starRequired: 4,
    label: 'Upgrade to Recycling Trash Room',
  },
]

/** Star at which a shaft kind unlocks (glass is the only late one). */
export const SHAFT_STAR_REQUIRED: Record<ShaftKind, StarLevel> = {
  standard: 1,
  express: 1,
  service: 1,
  glass: 4,
}

/**
 * Cost of a below-ground slab tile (excavation), per the "Slab / excavation |
 * $50 / $500" row in docs/games/tower-throwback.md. Above-ground slab tiles use
 * ITEM_DEFS.slab.cost ($50); underground digging substitutes this.
 */
export const EXCAVATION_COST = 500

export function itemDef(kind: ItemKind): ItemDef {
  return ITEM_DEFS[kind]
}

export function shaftDef(kind: ShaftKind): ShaftDef {
  return SHAFT_DEFS[kind]
}

/**
 * Availability = f(star, map). Uses maxStarReached (star demotion never
 * restricts building) and the map's disallowed list.
 */
export function isItemAvailable(kind: ItemKind, maxStarReached: StarLevel, map: MapDefinition): boolean {
  return ITEM_DEFS[kind].starRequired <= maxStarReached && !map.disallowedItems.includes(kind)
}

export function isShaftAvailable(kind: ShaftKind, maxStarReached: StarLevel, map: MapDefinition): boolean {
  return SHAFT_STAR_REQUIRED[kind] <= maxStarReached && !map.disallowedItems.includes(kind)
}

export function upgradesFor(kind: ItemKind, maxStarReached: StarLevel): UpgradePath[] {
  return UPGRADE_PATHS.filter((path) => path.appliesTo.includes(kind) && path.starRequired <= maxStarReached)
}
