/**
 * Phase boundary, not a working HTTP client.
 * Course JSON is governed by data/mandarin-course.schema.json.
 * Claude implements a mock gateway; Codex implements the same interface over Laravel.
 */
export type CourseIdentity = { courseId: string; contentVersion: string };
export type AudioSourceRef =
  | { sourceKind: 'utterance' | 'target' | 'support'; sourceId: string; variant: 'normal' | 'slow' }
  | { sourceKind: 'sfx'; sourceId: string; variant: 'default' };
export type AudioErrorCode =
  | 'not_available_in_preview' | 'generation_disabled' | 'sign_in_required'
  | 'provider_unconfigured' | 'unsupported_language' | 'unsupported_voice'
  | 'budget_exhausted' | 'provider_unavailable' | 'storage_unavailable'
  | 'asset_missing' | 'unknown_source';
export type AudioResolution =
  | { state: 'preview'; source: AudioSourceRef; delivery: 'simulated' | 'device_voice'; message: string }
  | { state: 'ready'; source: AudioSourceRef; assetId: string; url: string;
      expiresAt: string | null; contentHash: string; contentType: string;
      durationMs: number; provenance: 'synthesized_speech' | 'procedural_sfx' }
  | { state: 'queued' | 'generating'; source: AudioSourceRef; requestId: string;
      pollUrl: string; retryAfterMs: number }
  | { state: 'failed' | 'unavailable'; source: AudioSourceRef; code: AudioErrorCode;
      retryable: boolean; retryAfterMs: number | null; message: string };
export type AudioBatchRequest = CourseIdentity & { sources: AudioSourceRef[] };
export type AudioBatchResponse = CourseIdentity & { results: AudioResolution[] };
export type RuntimeMode = 'preview' | 'live';
export type SaveState = 'local_preview' | 'guest_local' | 'saving' | 'saved' | 'offline' | 'sign_in_required' | 'conflict';
export type Bootstrap<TCourse> = {
  runtime: RuntimeMode; course: TCourse;
  account: { signedIn: boolean; accountPartitionId: string | null };
  capabilities: { canGenerateAudio: boolean; canSaveToAccount: boolean; hasDistinctMandarinVoices: boolean };
  audio: AudioBatchResponse; serverTime: string;
};
export type AudioEvidence = {
  status: 'completed' | 'failed' | 'skipped' | 'not_required' | 'simulated';
  normalPlayCount: number; slowPlayCount: number; interrupted: boolean;
};
/** The server validates fields by kind, resolves target IDs, and computes correctness. */
export type PracticeEvent = CourseIdentity & {
  schemaVersion: 1; clientEventId: string; clientInstanceId: string; sessionId: string;
  clientOccurredAt: string; opportunityId: string | null;
  kind: 'response' | 'teaching_exposure' | 'help_revealed' | 'node_complete' | 'scene_complete' | 'checkpoint_exposure';
  mode: 'lesson' | 'review' | 'extra_practice' | 'checkpoint' | 'preview';
  sceneId: string | null; nodeId: string | null; exerciseId: string | null;
  source: AudioSourceRef | null; responseAction: 'answer' | 'dont_know' | 'skip' | null;
  selectedOptionId: string | null;
  orderedTileIds: string[] | null; textHelpUsed: boolean; pinyinHelpUsed: boolean;
  audioEvidence: AudioEvidence;
};
export type EventAcknowledgment = {
  clientEventId: string; status: 'accepted' | 'already_present' | 'rejected';
  canonicalSequence: number | null; serverAcceptedAt: string | null;
  correctness: 'correct' | 'incorrect' | 'unscored' | null;
  grade: 'Again' | 'Hard' | 'Good' | null;
  reasonCode: string | null;
};
export type AppendResult = { acknowledgments: EventAcknowledgment[]; lastSequence: number };
export type ProgressProjection = CourseIdentity & {
  lastSequence: number; completedNodeIds: string[]; completedSceneIds: string[];
  currentNodeId: string; dueTargetIds: string[]; checkpointExposedIds: string[];
  schedulerVersion: string; schedulerConfigHash: string;
  /** Exact card schema is defined by the pinned scheduler adapter, never by UI components. */
  listeningCards: Record<string, unknown>;
};
export interface MandarinGateway<TCourse> {
  bootstrap(signal?: AbortSignal): Promise<Bootstrap<TCourse>>;
  resolveAudio(request: AudioBatchRequest, signal?: AbortSignal): Promise<AudioBatchResponse>;
  pollAudio(requestId: string, signal?: AbortSignal): Promise<AudioResolution>;
  getProgress(signal?: AbortSignal): Promise<ProgressProjection>;
  appendEvents(events: PracticeEvent[], signal?: AbortSignal): Promise<AppendResult>;
}
/** Images are authored assets. They are not generated by the player's game session. */
export type VisualAsset = {
  id: string; src: string; fallbackSrc: string; kind: 'scene_poster' | 'portrait' | 'texture';
  width: number; height: number; hasAlpha: boolean; alt: string;
};
