import type { ChicksLevelDef } from './levelTypes'

/** Phase 1 — Basics (1–5): movement, chips, socket, exit, keys/doors. */
export const PHASE1_LEVELS: readonly ChicksLevelDef[] = [
  {
    id: 1,
    title: 'First Steps',
    grid: [
      '#########',
      '#...c...#',
      '#.......#',
      '#.c.@.c.#',
      '#...?...#',
      '#...c...#',
      '####S####',
      '####E####',
      '#########',
    ],
    par: 16,
    hint: 'Collect every chip 💠 to open the socket, then step through to the exit.',
  },
  {
    id: 2,
    title: 'Lock & Key',
    grid: [
      '###########',
      '#c.y#c....#',
      '##.##.###.#',
      '#.@.Y.....#',
      '#...#..####',
      '#...#..S.E#',
      '###########',
    ],
    par: 21,
  },
  {
    id: 3,
    title: 'Four Doors',
    grid: [
      '#########',
      '#@.g#..b#',
      '#...R...#',
      '#r..#...#',
      '#####B###',
      '#...#..y#',
      '##..Y...#',
      '#EG.#...#',
      '#########',
    ],
    par: 32,
  },
  {
    id: 4,
    title: 'Green Means Go',
    grid: [
      '###########',
      '#g..#....c#',
      '#...G.....#',
      '#@..#.....#',
      '##G#####G##',
      '#...#.....#',
      '#...#..####',
      '#c..#..GSE#',
      '###########',
    ],
    par: 36,
  },
  {
    id: 5,
    title: 'Key Economy',
    grid: [
      '#############',
      '#y....#c....#',
      '###.@.Y.....#',
      '#.....#######',
      '#.##..#.....#',
      '#.#y..Yc....#',
      '#.##..#######',
      '#.....#.....#',
      '#.....Y.#####',
      '#y....#SE####',
      '#############',
    ],
    par: 43,
  },
]
