import type { LevelDef, PiecePlacement } from './levelTypes'

const P = (pieceId: PiecePlacement['pieceId'], col: number, row: number, variant = 0, flipped = false): PiecePlacement => ({
  pieceId,
  col,
  row,
  variant,
  flipped,
})

const EMPTY = { blocks: [], pegs: [], fixed: [], noBuild: [] } as const

export const LEVELS: readonly LevelDef[] = [
  {
    ...EMPTY,
    id: 1,
    title: 'First Drop',
    cols: 5,
    rows: 6,
    start: { col: 1, row: 0 },
    goal: { col: 2, row: 4 },
    blocks: [{ col: 3, row: 3, w: 1, h: 2 }],
    inventory: { 'ramp-steep': 1 },
    par: { two: 1, three: 1 },
    hint: 'Put a ramp under the marble so it rolls into the basket.',
    tutorial: { pieceId: 'ramp-steep', cell: { col: 1, row: 3 } },
    solution: [P('ramp-steep', 1, 3)],
  },
  {
    ...EMPTY,
    id: 2,
    title: 'Zig-Zag',
    cols: 6,
    rows: 6,
    start: { col: 0, row: 0 },
    goal: { col: 1, row: 5 },
    fixed: [P('curve', 0, 1), P('track-long', 1, 1)],
    blocks: [{ col: 4, row: 1, w: 1, h: 3 }, { col: 0, row: 3, w: 1, h: 3 }],
    inventory: { 'ramp-steep': 3 },
    par: { two: 3, three: 2 },
    hint: 'Tap a placed ramp, then Flip it to point the other way.',
    solution: [P('ramp-steep', 3, 2, 0, true), P('ramp-steep', 2, 3, 0, true)],
  },
  {
    ...EMPTY,
    id: 3,
    title: 'Mind the Gap',
    cols: 8,
    rows: 5,
    start: { col: 0, row: 0 },
    goal: { col: 6, row: 2 },
    fixed: [P('curve', 0, 1), P('track-long', 1, 1), P('track-short', 5, 1)],
    blocks: [{ col: 7, row: 1, w: 1, h: 2 }],
    inventory: { 'track-short': 2, 'track-long': 1 },
    par: { two: 2, three: 1 },
    hint: 'Bridge the gap with straight track.',
    solution: [P('track-long', 3, 1)],
  },
  {
    ...EMPTY,
    id: 4,
    title: 'Turn Around',
    cols: 6,
    rows: 6,
    start: { col: 0, row: 0 },
    goal: { col: 2, row: 4 },
    fixed: [P('curve', 0, 1), P('track-long', 1, 1), P('track-long', 3, 1), P('ramp-gentle', 3, 3, 0, true)],
    blocks: [{ col: 1, row: 3, w: 1, h: 2 }],
    inventory: { uturn: 1, curve: 1 },
    par: { two: 2, three: 1 },
    hint: 'A U-Turn sends the marble back the way it came, one row lower.',
    solution: [P('uturn', 5, 1)],
  },
  {
    ...EMPTY,
    id: 5,
    title: 'Tube Station',
    cols: 6,
    rows: 7,
    start: { col: 1, row: 0 },
    goal: { col: 4, row: 6 },
    pegs: [{ col: 1, row: 3 }, { col: 3, row: 4 }, { col: 2, row: 5 }],
    blocks: [{ col: 5, row: 4, w: 1, h: 3 }],
    inventory: { tube: 4, 'tube-elbow': 2 },
    par: { two: 6, three: 5 },
    hint: 'Tubes keep the marble on course. Rotate a tube to lay it flat.',
    solution: [P('tube', 1, 1), P('tube-elbow', 1, 2), P('tube', 2, 2, 1), P('tube', 3, 2, 1), P('tube-elbow', 4, 2, 1)],
  },
  {
    ...EMPTY,
    id: 6,
    title: 'Bank Shot',
    cols: 7,
    rows: 7,
    start: { col: 1, row: 0 },
    goal: { col: 5, row: 6 },
    blocks: [{ col: 2, row: 3, w: 3, h: 1 }, { col: 6, row: 1, w: 1, h: 6 }],
    inventory: { bumper: 2 },
    par: { two: 2, three: 1 },
    hint: 'Bumpers are bouncy. Angle one to bank the marble sideways.',
    solution: [P('bumper', 1, 2)],
  },
  {
    ...EMPTY,
    id: 7,
    title: 'Big Jump',
    cols: 7,
    rows: 6,
    start: { col: 0, row: 0 },
    goal: { col: 5, row: 4 },
    fixed: [P('curve', 0, 1), P('ramp-steep', 1, 2), P('ramp-steep', 2, 3)],
    blocks: [{ col: 6, row: 2, w: 1, h: 3 }, { col: 5, row: 5, w: 2, h: 1 }],
    noBuild: [{ col: 4, row: 3 }, { col: 4, row: 4 }, { col: 4, row: 5 }],
    inventory: { kicker: 1, 'track-short': 1 },
    par: { two: 1, three: 1 },
    hint: 'A Jump flings a fast marble through the air.',
    solution: [P('kicker', 3, 3)],
  },
  {
    ...EMPTY,
    id: 8,
    title: 'Spring Up',
    cols: 4,
    rows: 7,
    start: { col: 0, row: 0 },
    goal: { col: 2, row: 5 },
    blocks: [{ col: 1, row: 6, w: 3, h: 1 }, { col: 3, row: 2, w: 1, h: 4 }],
    inventory: { launcher: 1, trampoline: 1 },
    par: { two: 1, three: 1 },
    hint: 'The Launcher fires the marble up and away the moment it lands.',
    solution: [P('launcher', 0, 5)],
  },
  {
    ...EMPTY,
    id: 9,
    title: 'Peg Field',
    cols: 7,
    rows: 8,
    start: { col: 3, row: 0 },
    goal: { col: 5, row: 7 },
    pegs: [{ col: 3, row: 2 }, { col: 2, row: 3 }, { col: 4, row: 3 }, { col: 3, row: 4 }],
    blocks: [{ col: 1, row: 2, w: 1, h: 3 }, { col: 5, row: 2, w: 1, h: 3 }],
    inventory: { funnel: 1, tube: 2, 'tube-elbow': 2 },
    par: { two: 5, three: 4 },
    hint: 'A Funnel catches a marble wherever it bounces.',
    solution: [P('funnel', 2, 5), P('tube-elbow', 3, 6), P('tube', 4, 6, 1), P('tube-elbow', 5, 6, 1)],
  },
  {
    ...EMPTY,
    id: 10,
    title: 'Switchback',
    cols: 6,
    rows: 7,
    start: { col: 0, row: 0 },
    goal: { col: 3, row: 6 },
    fixed: [P('curve', 0, 1)],
    blocks: [{ col: 4, row: 5, w: 1, h: 2 }, { col: 3, row: 4, w: 2, h: 1 }],
    inventory: { 'track-long': 3, 'track-short': 2, uturn: 2, 'ramp-gentle': 2 },
    par: { two: 8, three: 7 },
    hint: 'Back and forth: U-Turns on both sides make a switchback.',
    solution: [
      P('track-long', 1, 1),
      P('track-long', 3, 1),
      P('uturn', 5, 1),
      P('ramp-gentle', 3, 3, 0, true),
      P('track-long', 1, 3),
      P('uturn', 0, 3, 0, true),
      P('ramp-gentle', 1, 5),
    ],
  },
  {
    ...EMPTY,
    id: 11,
    title: 'Bounce House',
    cols: 7,
    rows: 7,
    start: { col: 0, row: 0 },
    goal: { col: 5, row: 4 },
    blocks: [{ col: 5, row: 5, w: 2, h: 2 }, { col: 6, row: 1, w: 1, h: 4 }],
    inventory: { bumper: 1, trampoline: 1, 'ramp-steep': 1 },
    par: { two: 3, three: 2 },
    hint: 'Bank off a Bumper, then let a Trampoline bounce you up onto the ledge.',
    solution: [P('bumper', 0, 1), P('trampoline', 3, 6)],
  },
  {
    ...EMPTY,
    id: 12,
    title: 'Grand Machine',
    cols: 8,
    rows: 10,
    start: { col: 1, row: 0 },
    goal: { col: 4, row: 9 },
    fixed: [P('track-short', 6, 3)],
    blocks: [{ col: 5, row: 6, w: 3, h: 4 }, { col: 1, row: 5, w: 1, h: 1 }],
    noBuild: [{ col: 5, row: 2 }, { col: 5, row: 3 }],
    inventory: { tube: 1, 'tube-elbow': 1, 'track-long': 1, kicker: 1, uturn: 1, 'ramp-gentle': 2, bumper: 1, launcher: 1, funnel: 1 },
    par: { two: 9, three: 8 },
    hint: 'Every piece has a job. Build it one stage at a time and test as you go.',
    solution: [
      P('tube', 1, 1),
      P('tube-elbow', 1, 2),
      P('track-long', 2, 2),
      P('kicker', 4, 2),
      P('uturn', 7, 3),
      P('ramp-gentle', 5, 5, 0, true),
      P('ramp-gentle', 3, 6, 0, true),
      P('launcher', 0, 9),
    ],
  },
]
