import { runStarProgression } from '../engine/__tests__/starProgressionScenario'
import { stepEngine } from '../engine/engine'
import { exportSandbox, loadSandbox, saveSandbox } from '../gameProgress'
import type { EngineCommand } from '../gameTypes'

/**
 * Deterministic generator + regeneration guard for the committed end-of-game
 * fixture (JEST_INCLUDE_SLOW_TESTS=1 only).
 *
 * The fixture is the completed run of `runStarProgression` (5★ + TOWER),
 * serialized through the REAL v2 save wire (`saveSandbox` → `loadSandbox` →
 * `exportSandbox`). The floor-99 cathedral is demolished first: `towerAchieved`
 * persists through demolition (the crown is never revoked), and a floor-99 /
 * 2-storey unit fails `parseUnit`'s `floor + storeys - 1 <= FLOOR_MAX(99)` guard
 * — so a cathedral in the payload cannot round-trip (issue #1626). Demolishing
 * it is both the in-game "crown persists" behavior and what keeps the fixture
 * importable.
 *
 * Regenerate with:  TOWER_WRITE_FIXTURE=1 JEST_INCLUDE_SLOW_TESTS=1 \
 *   pnpm test -- completedTowerFixture.slow
 * Otherwise this test asserts the freshly generated bytes equal the committed
 * fixture, proving it is reproducible and up to date.
 *
 * node:fs / process are reached through declared ambients (the frontend
 * type-check config carries no node types — same pattern as
 * `tests-ts/jestConfig.test.ts`); Jest provides the real implementations.
 */

declare function require(moduleName: string): unknown
declare const process: { env: Record<string, string | undefined>; cwd(): string }

interface FsLike {
  existsSync(path: string): boolean
  readFileSync(path: string, encoding: 'utf8'): string
  writeFileSync(path: string, data: string): void
}

const fs = require('node:fs') as FsLike

const FIXTURE_PATH = `${process.cwd()}/resources/js/games/tower-throwback/__tests__/fixtures/completed-tower.v2.json`

function generateCompletedTowerJson(): string {
  window.localStorage.clear()
  const { state } = runStarProgression()

  // Crown persists through demolition; removing the floor-99 cathedral is what
  // lets the completed state round-trip through the save contract.
  const cathedral = state.units.find((u) => u.kind === 'cathedral')
  if (cathedral) {
    const demolish: EngineCommand = { type: 'demolishUnit', unitId: cathedral.id }
    const events = stepEngine(state, [demolish], 0)
    const rejected = events.find((e) => e.type === 'placementRejected')
    if (rejected) {
      throw new Error(`cathedral demolish rejected: ${JSON.stringify(rejected)}`)
    }
  }

  const write = saveSandbox(state, 'slot-c')
  if (!write.ok) {
    throw new Error(`saveSandbox failed: ${write.reason}`)
  }
  const saved = loadSandbox('slot-c')
  if (!saved) {
    throw new Error('loadSandbox returned null for the freshly generated completed tower')
  }
  return `${exportSandbox(saved)}\n`
}

describe('completed-tower fixture generator', () => {
  it(
    'regenerates the committed end-of-game fixture deterministically',
    () => {
      const generated = generateCompletedTowerJson()

      if (process.env.TOWER_WRITE_FIXTURE === '1') {
        fs.writeFileSync(FIXTURE_PATH, generated)
      }

      expect(fs.existsSync(FIXTURE_PATH)).toBe(true)
      const committed = fs.readFileSync(FIXTURE_PATH, 'utf8')
      expect(generated).toEqual(committed)
    },
    120_000,
  )
})
