import type { ItemKind, ShaftKind } from '../gameTypes'

export const BUILD_TOOL_ICON_FILES = {
  slab: 'slab.svg',
  lobby: 'lobby.svg',
  skylobby: 'skylobby.svg',
  skybridge: 'skybridge.svg',
  stairs: 'stairs.svg',
  escalator: 'escalator.svg',
  officeS: 'officeS.svg',
  officeM: 'officeM.svg',
  officeL: 'officeL.svg',
  aptStudio: 'aptStudio.svg',
  apt1br: 'apt1br.svg',
  apt2br: 'apt2br.svg',
  aptPenthouse: 'aptPenthouse.svg',
  restroom: 'restroom.svg',
  shop: 'shop.svg',
  fastfood: 'fastfood.svg',
  foodCourt: 'foodCourt.svg',
  restaurant: 'restaurant.svg',
  fancyRestaurant: 'fancyRestaurant.svg',
  movieTheater: 'movieTheater.svg',
  fitness: 'fitness.svg',
  pool: 'pool.svg',
  spa: 'spa.svg',
  conferenceCenter: 'conferenceCenter.svg',
  eventSpace: 'eventSpace.svg',
  hotelReception: 'hotelReception.svg',
  hotel1p: 'hotel1p.svg',
  hotel2p: 'hotel2p.svg',
  hotelSuite: 'hotelSuite.svg',
  housekeeping: 'housekeeping.svg',
  trashRoom: 'trashRoom.svg',
  recyclingCenter: 'recyclingCenter.svg',
  parkingRamp: 'parkingRamp.svg',
  parkingSpace: 'parkingSpace.svg',
  subway: 'subway.svg',
  securityOffice: 'securityOffice.svg',
  medicalClinic: 'medicalClinic.svg',
  cathedral: 'cathedral.svg',
  observationDeck: 'observationDeck.svg',
  standard: 'standard-elevator.svg',
  express: 'express-elevator.svg',
  service: 'service-elevator.svg',
  glass: 'glass-elevator.svg',
} as const satisfies Record<ItemKind | ShaftKind, string>

export const BUILD_TOOL_ICON_URLS = {
  slab: new URL('../assets/icons/slab.svg', import.meta.url).href,
  lobby: new URL('../assets/icons/lobby.svg', import.meta.url).href,
  skylobby: new URL('../assets/icons/skylobby.svg', import.meta.url).href,
  skybridge: new URL('../assets/icons/skybridge.svg', import.meta.url).href,
  stairs: new URL('../assets/icons/stairs.svg', import.meta.url).href,
  escalator: new URL('../assets/icons/escalator.svg', import.meta.url).href,
  officeS: new URL('../assets/icons/officeS.svg', import.meta.url).href,
  officeM: new URL('../assets/icons/officeM.svg', import.meta.url).href,
  officeL: new URL('../assets/icons/officeL.svg', import.meta.url).href,
  aptStudio: new URL('../assets/icons/aptStudio.svg', import.meta.url).href,
  apt1br: new URL('../assets/icons/apt1br.svg', import.meta.url).href,
  apt2br: new URL('../assets/icons/apt2br.svg', import.meta.url).href,
  aptPenthouse: new URL('../assets/icons/aptPenthouse.svg', import.meta.url).href,
  restroom: new URL('../assets/icons/restroom.svg', import.meta.url).href,
  shop: new URL('../assets/icons/shop.svg', import.meta.url).href,
  fastfood: new URL('../assets/icons/fastfood.svg', import.meta.url).href,
  foodCourt: new URL('../assets/icons/foodCourt.svg', import.meta.url).href,
  restaurant: new URL('../assets/icons/restaurant.svg', import.meta.url).href,
  fancyRestaurant: new URL('../assets/icons/fancyRestaurant.svg', import.meta.url).href,
  movieTheater: new URL('../assets/icons/movieTheater.svg', import.meta.url).href,
  fitness: new URL('../assets/icons/fitness.svg', import.meta.url).href,
  pool: new URL('../assets/icons/pool.svg', import.meta.url).href,
  spa: new URL('../assets/icons/spa.svg', import.meta.url).href,
  conferenceCenter: new URL('../assets/icons/conferenceCenter.svg', import.meta.url).href,
  eventSpace: new URL('../assets/icons/eventSpace.svg', import.meta.url).href,
  hotelReception: new URL('../assets/icons/hotelReception.svg', import.meta.url).href,
  hotel1p: new URL('../assets/icons/hotel1p.svg', import.meta.url).href,
  hotel2p: new URL('../assets/icons/hotel2p.svg', import.meta.url).href,
  hotelSuite: new URL('../assets/icons/hotelSuite.svg', import.meta.url).href,
  housekeeping: new URL('../assets/icons/housekeeping.svg', import.meta.url).href,
  trashRoom: new URL('../assets/icons/trashRoom.svg', import.meta.url).href,
  recyclingCenter: new URL('../assets/icons/recyclingCenter.svg', import.meta.url).href,
  parkingRamp: new URL('../assets/icons/parkingRamp.svg', import.meta.url).href,
  parkingSpace: new URL('../assets/icons/parkingSpace.svg', import.meta.url).href,
  subway: new URL('../assets/icons/subway.svg', import.meta.url).href,
  securityOffice: new URL('../assets/icons/securityOffice.svg', import.meta.url).href,
  medicalClinic: new URL('../assets/icons/medicalClinic.svg', import.meta.url).href,
  cathedral: new URL('../assets/icons/cathedral.svg', import.meta.url).href,
  observationDeck: new URL('../assets/icons/observationDeck.svg', import.meta.url).href,
  standard: new URL('../assets/icons/standard-elevator.svg', import.meta.url).href,
  express: new URL('../assets/icons/express-elevator.svg', import.meta.url).href,
  service: new URL('../assets/icons/service-elevator.svg', import.meta.url).href,
  glass: new URL('../assets/icons/glass-elevator.svg', import.meta.url).href,
} as const satisfies Record<ItemKind | ShaftKind, string>

export const HUD_ICON_FILES = {
  'toolbar.build': 'toolbar-build.svg',
  'toolbar.run': 'toolbar-run.svg',
  'toolbar.financials': 'toolbar-financials.svg',
  'toolbar.saves': 'toolbar-saves.svg',
  'toolbar.soundOn': 'toolbar-sound-on.svg',
  'toolbar.soundOff': 'toolbar-sound-off.svg',
  'toolbar.pause': 'toolbar-pause.svg',
  'toolbar.speed1': 'toolbar-speed-1.svg',
  'toolbar.speed2': 'toolbar-speed-2.svg',
  'toolbar.speed4': 'toolbar-speed-4.svg',
  'toolbar.speed8': 'toolbar-speed-8.svg',
  'toolbar.speed16': 'toolbar-speed-16.svg',
  'overlay.none': 'overlay-none.svg',
  'overlay.noise': 'overlay-noise.svg',
  'overlay.congestion': 'overlay-congestion.svg',
  'star.rating': 'star.svg',
  'star.progress': 'star-progress.svg',
  'star.tower': 'tower-crown.svg',
  vip: 'vip.svg',
  'incident.warning': 'incident-warning.svg',
  'incident.bombThreat': 'incident-bomb-threat.svg',
  'incident.cockroach': 'incident-cockroach.svg',
  'incident.repair': 'incident-repair.svg',
  'incident.request': 'incident-request.svg',
  'incident.vacancy': 'incident-vacancy.svg',
} as const

export const HUD_ICON_URLS = {
  'toolbar.build': new URL('../assets/icons/toolbar-build.svg', import.meta.url).href,
  'toolbar.run': new URL('../assets/icons/toolbar-run.svg', import.meta.url).href,
  'toolbar.financials': new URL('../assets/icons/toolbar-financials.svg', import.meta.url).href,
  'toolbar.saves': new URL('../assets/icons/toolbar-saves.svg', import.meta.url).href,
  'toolbar.soundOn': new URL('../assets/icons/toolbar-sound-on.svg', import.meta.url).href,
  'toolbar.soundOff': new URL('../assets/icons/toolbar-sound-off.svg', import.meta.url).href,
  'toolbar.pause': new URL('../assets/icons/toolbar-pause.svg', import.meta.url).href,
  'toolbar.speed1': new URL('../assets/icons/toolbar-speed-1.svg', import.meta.url).href,
  'toolbar.speed2': new URL('../assets/icons/toolbar-speed-2.svg', import.meta.url).href,
  'toolbar.speed4': new URL('../assets/icons/toolbar-speed-4.svg', import.meta.url).href,
  'toolbar.speed8': new URL('../assets/icons/toolbar-speed-8.svg', import.meta.url).href,
  'toolbar.speed16': new URL('../assets/icons/toolbar-speed-16.svg', import.meta.url).href,
  'overlay.none': new URL('../assets/icons/overlay-none.svg', import.meta.url).href,
  'overlay.noise': new URL('../assets/icons/overlay-noise.svg', import.meta.url).href,
  'overlay.congestion': new URL('../assets/icons/overlay-congestion.svg', import.meta.url).href,
  'star.rating': new URL('../assets/icons/star.svg', import.meta.url).href,
  'star.progress': new URL('../assets/icons/star-progress.svg', import.meta.url).href,
  'star.tower': new URL('../assets/icons/tower-crown.svg', import.meta.url).href,
  vip: new URL('../assets/icons/vip.svg', import.meta.url).href,
  'incident.warning': new URL('../assets/icons/incident-warning.svg', import.meta.url).href,
  'incident.bombThreat': new URL('../assets/icons/incident-bomb-threat.svg', import.meta.url).href,
  'incident.cockroach': new URL('../assets/icons/incident-cockroach.svg', import.meta.url).href,
  'incident.repair': new URL('../assets/icons/incident-repair.svg', import.meta.url).href,
  'incident.request': new URL('../assets/icons/incident-request.svg', import.meta.url).href,
  'incident.vacancy': new URL('../assets/icons/incident-vacancy.svg', import.meta.url).href,
} as const satisfies Record<keyof typeof HUD_ICON_FILES, string>

export const ALL_HUD_ICON_FILES = [
  ...Object.values(BUILD_TOOL_ICON_FILES),
  ...Object.values(HUD_ICON_FILES),
] as const
